import type { INodeProperties } from 'n8n-workflow';
import { organizationSlugProperty } from '../shared/organizationSlug';

export const checkoutIntentFields: INodeProperties[] = [
	organizationSlugProperty('checkoutIntent', ['create', 'get']),
	{
		displayName: 'Checkout Intent ID',
		name: 'checkoutIntentId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['get'] } },
		description: 'The ID of the checkout intent',
	},
	{
		displayName: 'Total Amount (Cents)',
		name: 'totalAmount',
		type: 'number',
		required: true,
		default: 0,
		typeOptions: { minValue: 0 },
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'Total amount in cents, taxes included (must equal the initial amount plus any terms)',
		routing: { send: { type: 'body', property: 'totalAmount' } },
	},
	{
		displayName: 'Initial Amount (Cents)',
		name: 'initialAmount',
		type: 'number',
		required: true,
		default: 0,
		typeOptions: { minValue: 0 },
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'Amount of the first term in cents, taxes included',
		routing: { send: { type: 'body', property: 'initialAmount' } },
	},
	{
		displayName: 'Item Name',
		name: 'itemName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'Description of the purchase (1-250 characters), e.g. "3 tickets"',
		routing: { send: { type: 'body', property: 'itemName' } },
	},
	{
		displayName: 'Back URL',
		name: 'backUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/back',
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'URL the contributor is sent to if they leave before paying',
		routing: { send: { type: 'body', property: 'backUrl' } },
	},
	{
		displayName: 'Error URL',
		name: 'errorUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/error',
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'URL called if the checkout process fails',
		routing: { send: { type: 'body', property: 'errorUrl' } },
	},
	{
		displayName: 'Return URL',
		name: 'returnUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/return',
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'URL called once the payment is completed',
		routing: { send: { type: 'body', property: 'returnUrl' } },
	},
	{
		displayName: 'Contains Donation',
		name: 'containsDonation',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		description: 'Whether the sale, or part of it, is a donation',
		routing: { send: { type: 'body', property: 'containsDonation' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['checkoutIntent'], operation: ['create'] } },
		options: [
			{
				displayName: 'Metadata',
				name: 'metadata',
				type: 'json',
				default: '{}',
				description: 'Free-form JSON metadata returned on the checkout intent (max 20,000 characters)',
				routing: { send: { type: 'body', property: 'metadata' } },
			},
		],
	},
];
